project:
  type: website
  output-dir: docs  
  resources: 
    - "*.mp3"

execute:
  freeze: auto

website:
  title: "notes"
  site-url: https://nealcaren.github.io/notes
  twitter-card: true
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/nealcaren
      - icon: twitter
        href: https://bsky.app/profile/haphazardsoc.bsky.social
      - icon: rss
        href: index.xml
format:
  html:
    theme: cosmos
    css: styles.css



