project:
  type: website
  output-dir: docs  
  resources: 
    - "*.mp3"
  render:
    - "*.ipynb"
    - "!drafts/"
    
execute:
  freeze: auto

listing:
  contents: posts
  feed: true

website:
  title: "notes"
  favicon: logo.png
  site-url: "https://nealcaren.github.io/notes"
  twitter-card: true
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/nealcaren
      - icon: twitter
        href: https://bsky.app/profile/haphazardsoc.bsky.social
format:
  html:
    theme: cosmos
    css: styles.css



