project:
  type: website
  output-dir: docs  
  resources: 
    - "*.mp3"

execute:
  freeze: auto

website:
  title: "notes"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/nealcaren
      - icon: twitter
        href: https://twitter.com/haphazardsoc
format:
  html:
    theme: cosmos
    css: styles.css



